env:
  global:
    - BROWSERSTACK_USERNAME=amitu
    - secure: IR0wK5lUp7keGUgxFq0OE7vz4dUtAJbOexJjlHLa7ioMHoNXGr1x9we1W7XU/b0+X0TwPLQKy8CZnlNowPBQNJcVKM8DMtqeH90GaimY4kD8BTC5gS0PWLS4P9cfCA/Px/OT2ynvR7dVfSTyEg7EDe2q3PUL9D6u1G9YHMpAQAo=
before_script: 
    - python -m SimpleHTTPServer > /dev/null &
    - pip install browserstack-local selenium --use-mirrors
    - browserstack-local $BROWSERSTACK_KEY localhost,8000,0 &
    - sleep 10
node_js:
    - "0.11"
language: node_js
script: 
    - python test.py
