language: python
python: 
- 2.7

before_script: 
  - python -m SimpleHTTPServer &
  - pip install browserstack-local selenium --use-mirrors --quiet
  - browserstack-local BROWSERSTACK_KEY localhost,8000,0 &
  - sleep 10
script:
  - python test.py
env:
  global:
    - BROWSERSTACK_USERNAME=amitu
    - secure: "dhaOR/0YLGlDj/AKFDgTbKx+6OXNt54XLVXvF0/+xCDT2UMPF0x0Z6+Zmw8F3NS9v7pHAIwUbM/dkAAIJCrWgvozxfRTW+oNPTrdw6CBS+C+BGxVkXh4TxXDJNuGHi6YNttEFnqPNgkynoEbXuvLj8Eem/nJyvqh0++doHHBmwQ="
